---

  - name: Install dependency software
    win_chocolatey:
      name: '{{ item }}'
      state: present
    with_items:
      - nodejs
      - git
      - steamcmd
      - vcredist2015
      - vcredist2013
      - vcbuildtools
      - directx
      - nssm
    notify: reboot windows
