---

  - name: include windows handlers
    include: ./windows_handlers.yml
    when: squad_server_os == 'windows'

  - name: include linux handlers
    include: ./linux_handlers.yml
    when: squad_server_os == 'linux'
